### ISSUE TITLE
Category Data is always empty.

### ISSUE THREAD

**Issue by arslancharyev31** [atenfyr/UAssetGUI#1]
Hello.
I've been trying to open uassets extracted from a pak of a shipped UE4 game. The Header List, Linked Sectors, and Section Information seem to work well, but not the Category Data. It has the sub-elements like Category Data 1, Category Data 2 but they all seem to have only Raw Data (0B). Also, opening any uasset file results in a "Uh-oh!" dialog, complaining about how it "Failed to verify parsing...". Any ideas why it happens?

**Comment by atenfyr** [comment]
Hi there,

Funnily enough, I just encountered this issue a few hours ago while looking at assets from another game; it seems to only occur with uassets which were built with separate bulk data files, since UAssetAPI has little to no support for .uexp and .umap files. I've added some rough support for .uexp files in the latest commit of UAssetAPI that should allow reading and hopefully writing of .uassets and .uexp files just fine, so for now, pulling that down should do the trick for UAssetGUI. Do note, however, that UAssetAPI was not originally built to support .uexp files whatsoever, so you may experience some problems!

Atenfyr
