### ISSUE TITLE
Unable to parse all The Outer World files.

### ISSUE THREAD

**Issue by Valkynaz141** [atenfyr/UAssetGUI#16]
Program is unable to parse specific files for the game The Outer Worlds (Appears to work with most*, but ones inside the item section at least do not)

Simply trying to load the .uasset file results in at least 1 failure to parse
![UAssetGUI_upXKCjycM2](https://user-images.githubusercontent.com/96696306/147415520-dc7c37dc-6131-46c0-9384-b9de7cbfd5c0.png)

![UAssetGUI_RpUtFll3sK](https://user-images.githubusercontent.com/96696306/147415523-dc7bb18f-1687-49f1-a07c-5bcbf0fd6a31.png)

Have tried some other files and all appear to work as intended

Attached is the file that I have been trying to edit
[Drug_SC_Adreno.zip](https://github.com/atenfyr/UAssetGUI/files/7777319/Drug_SC_Adreno.zip)

**Comment by atenfyr** [comment]
atenfyr/UAssetAPI@56815c9 fixes the issue in which the export is unable to parse, but I'm unable to maintain binary equality since it would seem to me that the changes that occur are due to corruption in the original file or due to a fundamental flaw or change in the asset format (which would be strange since you say that most assets parse correctly!) Please only send in assets that have not been modified with an external tool after being cooked by the engine
