### ISSUE TITLE
Wrong offset address?

### ISSUE THREAD

**Issue by kotoricon** [atenfyr/UAssetGUI#36]
I'm not sure this is a bug or just something wrong on me, look like the tool's given memory offset address is wrong.
The same file offset address from [AssetEditor](https://github.com/kaiheilos/Utilities) and UAssetGUI is different, I'm pretty sure the AssetEditor is right address because I already test it in game. any help for this?

![AssetEditor_5kH5ilfYje](https://user-images.githubusercontent.com/8659834/195343926-4a3837ff-4796-44a1-a26c-247766bd3d29.png)
[offsetbug.zip](https://github.com/atenfyr/UAssetGUI/files/9764856/offsetbug.zip)

**Comment by atenfyr** [comment]
In the .uasset format, most tagged properties are serialized like this, from start to finish:

- An 8-byte FName that corresponds to the property name
- An 8-byte FName that corresponds to the property type
- A 4-byte integer that corresponds to the length of the data in the property
- A 4-byte integer used for distinguishing between different properties with the same name
- A single byte that is a boolean which corresponds to whether this property has a GUID. This is nearly always 0, but if it is 1, then a 16-byte GUID follows
- The data in the property (which varies by property type)

Heilos's asset editor positions the offset at the start of the data in the property (see the last bullet point), whereas UAssetGUI positions the offset at the beginning of the entire property definition, which leads to UAssetGUI's displayed offset typically being 8 + 8 + 4 + 4 + 1 = 25 bytes before the offset displayed by Heilos's asset editor, as you observed. UAssetGUI uses this as a reference point because it means that the serial offset serves as a marker for exactly where information corresponding to the last property ended and information about the next property began (in other words, any given property in the asset can be wholly represented given two offsets, its own offset and the offset of the next property). You could certainly make the case that using this definition of "serial offset" undermines the point of displaying it at all because it makes finding information in a hex editor more difficult, however ;)
