### ISSUE TITLE
Object reference not set

### ISSUE THREAD

**Issue by StijnDark** [atenfyr/UAssetGUI#48]
I am facing an issue on version 1.0.0.7 on UE 4.25 where it says "Failed to save! Object reference not set to an instance of an object." once I'm saving it. 

Is it possible to create something so it knows where the issue is located so you can easily try to fix it? It could be usefu
l and will save a lot of time (especially with larger files).

Or maybe mark the location of the error with a red color. 

I have copied and pasted an export to another huge file. And with this error it's impossible to find out where the issue is located. (If you'd like to look into the 2 files i'd like to merge, I will attach them this message!)
I hope you will consider this feature 😃 

[PlayerControllerF.zip](https://github.com/atenfyr/UAssetGUI/files/10481930/PlayerControllerF.zip)
![Screenshot_1904](https://user-images.githubusercontent.com/81808936/214100917-28d78a93-da9d-4f8d-b87a-4d43ef5624e2.png)
![Screenshot_1905](https://user-images.githubusercontent.com/81808936/214100920-c2649f1b-fe69-4e2c-aeff-92e34165b6f0.png)

**Comment by atenfyr** [comment]
Sorry for the late response! Unfortunately, due to the nature of this kind of error it is pretty difficult to pin down exactly where the issue lies within an asset; UAssetGUI is designed to not let you even input any data that wouldn't make sense when serialized in the .uasset format, with a few exceptions (such as empty StructProperties with custom serialization) that have clear exception text. When UAssetGUI is throwing this kind of error, it is likely because there is some inherent bug or a higher-level logical error that should not be allowed to be occur in the first place, and not because the data that you inputted is strictly invalid. Detecting and throwing readable errors about such logical errors is an ongoing project, and not a single thing I can easily pin down and fix unfortunately.

Although in theory the JSON format that is saved to the clipboard is independent enough to carry data between assets, copying and pasting exports between assets nearly always requires significant work in adjusting data to match the environment of the new asset, such as import/export references, export dependencies, etc. It is possible that there is some strange logical error that occurred because of this inherent inconsistency between assets, but I can't really be sure without knowing the full details about what you are copying over and information about the stack trace (which I should probably log in the first place when it fails to save...). I would suggest that you re-examine the export that you are trying to copy between assets and make sure that you have adjusted whatever is necessary for the environment of the new asset.

Thanks for using UAssetGUI
