### ISSUE TITLE
Days Gone 4.11 File Support

### ISSUE THREAD

**Issue by sEmreCaNw** [atenfyr/UAssetGUI#63]
File samples for Days Gone https://www.mediafire.com/file/toeeepm8jyd3yow/DaysGoneFileSamples.rar/file

**Comment by atenfyr** [comment]
Fixed in atenfyr/UAssetAPI@2c65888. Some notes:
- The engine has clearly been extensively modified, which means that there may be some further issues with custom serialization. If you experience further issues, let me know! I may have to just add a special option for Days Gone serialization in UAssetGUI.
- Days Gone does not serialize inner array tag information, which means that any struct with custom serialization (e.g. vectors, rotators) will fail. You can solve this by dumping a set of mappings with with [UE4SS](https://github.com/UE4SS-RE/RE-UE4SS) or [UnrealMappingsDumper](https://github.com/OutTheShade/UnrealMappingsDumper) and importing them with the latest commit of UAssetGUI, but those tools will more than likely not work out-of-the-box on a 4.11 game.

**Comment by sEmreCaNw** [comment]
> Fixed in [atenfyr/UAssetAPI@2c65888](https://github.com/atenfyr/UAssetAPI/commit/2c65888). Some notes:
> 
> * The engine has clearly been extensively modified, which means that there may be some further issues with custom serialization. If you experience further issues, let me know! I may have to just add a special option for Days Gone serialization in UAssetGUI.
> * Days Gone does not serialize inner array tag information, which means that any struct with custom serialization (e.g. vectors, rotators) will fail. You can solve this by dumping a set of mappings with with [UE4SS](https://github.com/UE4SS-RE/RE-UE4SS) or [UnrealMappingsDumper](https://github.com/OutTheShade/UnrealMappingsDumper) and importing them with the latest commit of UAssetGUI, but those tools will more than likely not work out-of-the-box on a 4.11 game.

Thank you so much,yes engine is heavily  modified but surprisingly cooked custom mesh,texture,material and blueprint files from Epic Store UE 4.11 Editor works just fine.Your tool cant open the orginal Days Gone assets but its able to open custom assets from the regular 4.11 editor, however it gives an warning,here is a comparation video(a note i'm not using the fixed version,i will try now)

https://github.com/atenfyr/UAssetGUI/assets/120100309/6810c414-8688-4580-87f7-5c5b31ee9879
